# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/ktexttemplate': '@latest-kf6'
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'pim/akonadi' : '@latest-kf6'
    'pim/grantleetheme' : '@latest-kf6'
    'pim/kontactinterface' : '@latest-kf6'
    'pim/kpimtextedit' : '@latest-kf6'
    'pim/libkdepim' : '@latest-kf6'
    'pim/pimcommon' : '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]      
